// Sample portfolio content — realistic institutional finance / IB / strategy content.
export const OWNER = {
  name: 'Deepak',
  role: 'Investment Banking · Strategic Finance · M&A · Corporate Development',
  currentRole: 'Investment Banking Analyst · M&A + Strategic Finance',
  location: 'Mumbai · Singapore · Remote',
  email: 'deepak@portfolio.dev',
  linkedin: 'https://linkedin.com/in/example',
  tagline: 'Building institutional-grade financial intelligence — from three-statement operating models and valuation to M&A execution and AI-augmented deal workflows.',
  bio: 'Seven years across corporate development, FP&A, and M&A research — most recently supporting cross-border sell-side mandates and building AI-augmented deal-sourcing pipelines used across sector teams. Comfortable moving from cohort-level revenue builds to IC-ready return bridges in the same afternoon.',
  portraitFocal: { x: 50, y: 30 },
  metrics: [
    { value: '$4.8B+', label: 'Transaction value supported' },
    { value: '60', label: 'Financial models built' },
    { value: '32', label: 'Deal & strategy engagements' },
    { value: '184', label: 'Acquisition targets evaluated' },
  ],
  availability: 'Open to Investment Banking Analyst, Corporate Development, and Strategic Finance roles at bulge-bracket banks, elite boutiques, MBB consulting, and top buy-side platforms. Interview windows: weekday evenings IST / weekend AM.',
};

export const EXPERTISE_CHIPS = [
  'Strategic Finance',
  'Valuation',
  'M&A',
  'Investment Banking',
  'FP&A',
  'Corporate Development',
  'AI for Finance',
];

export const CHAPTERS = [
  {
    id: 'why-finance',
    kicker: 'Chapter I',
    title: 'Why Finance',
    body: 'Finance is the language a business uses to describe its own future. I picked this craft because it forces intellectual honesty — a model either survives contact with reality, or it does not. Everything I build is designed to survive that contact and to give investment committees a defensible answer.',
  },
  {
    id: 'how-i-think',
    kicker: 'Chapter II',
    title: 'How I Think',
    principles: [
      { t: 'Assumptions are the product.', d: 'A valuation is only as defensible as the operating assumptions you can walk an IC through, line by line.' },
      { t: 'Signal over surface.', d: 'One decision-grade waterfall beats twenty decorative charts. Board packs get shorter, not longer.' },
      { t: 'Compound with tooling.', d: 'Python, SQL and LLM workflows remove grunt work so judgement gets more reps — and the coverage universe expands.' },
      { t: 'Write the memo first.', d: 'If the investment thesis cannot be written in one page before the model, the analysis is not done.' },
    ],
  },
];

/* ---------------- Selected Transactions & Strategic Projects (Tombstones) ---------------- */

export const TRANSACTIONS = [
  {
    id: 't-arohan-ipo',
    dealNumber: '#001',
    year: 2024,
    target: 'Arohan Financial Services',
    subtitle: 'Pre-IPO diligence & valuation support',
    type: 'IPO',
    size: '₹1,850 Cr',
    sector: 'Financial Services · NBFC / Microfinance',
    role: 'Financial modelling · Valuation range · Peer benchmarking',
    tools: ['Excel', 'Bloomberg', 'Capital IQ'],
    outcome: 'Anchored the pre-IPO valuation band; supported management-Q&A prep for the institutional roadshow.',
    projectId: null,
  },
  {
    id: 't-varun-valuation',
    dealNumber: '#002',
    year: 2024,
    target: 'Varun Beverages',
    subtitle: 'Enterprise valuation — trading & transaction comparables',
    type: 'Valuation',
    size: '$9.2B EV',
    sector: 'Consumer · Beverages',
    role: 'DCF · Trading comparables · Precedent transactions',
    tools: ['Excel', 'CapIQ', 'PitchBook'],
    outcome: 'Triangulated valuation range with 22 listed peers and 14 precedent deals; sensitised WACC 8.5%–11.5%.',
    projectId: null,
  },
  {
    id: 't-tsmc-model',
    dealNumber: '#003',
    year: 2024,
    target: 'TSMC',
    subtitle: 'Three-statement operating model & scenario analysis',
    type: 'Operating Model',
    size: '$800B+ market cap',
    sector: 'Semiconductors',
    role: 'Three-statement build · Fab-utilisation sensitivities',
    tools: ['Excel', 'Python', 'FactSet'],
    outcome: 'Fab-level revenue build across 3, 5 and 7 nm nodes; downside scenario on capex deferral through 2027.',
    projectId: null,
  },
  {
    id: 't-tmt-sellside',
    dealNumber: '#004',
    year: 2024,
    target: 'Cross-Border TMT Platform',
    subtitle: 'Sell-side advisory — 210 buyers screened',
    type: 'M&A · Sell-Side',
    size: '$2.4B EV',
    sector: 'Technology, Media & Telecom',
    role: 'CIM authorship · Buyer landscape · Synergy bridge',
    tools: ['Excel', 'Capital IQ', 'PowerPoint'],
    outcome: 'Shortlisted 14 → 3 confirmatory bids at blended 14.6x forward EBITDA; 11-week closing timeline.',
    projectId: 'ma-tmt-2b',
  },
  {
    id: 't-industrial-lbo',
    dealNumber: '#005',
    year: 2024,
    target: 'Industrial Coatings Co.',
    subtitle: 'PE take-private LBO · returns bridge attribution',
    type: 'LBO · Buy-Side',
    size: '$780M EV · 5.2x leverage',
    sector: 'Industrials',
    role: 'LBO model · Debt schedule (3 tranches) · IC memo',
    tools: ['Excel', 'Python'],
    outcome: 'Base-case 3.1x MOIC / 24% IRR — bridge: 44% EBITDA growth, 31% deleveraging, 25% multiple expansion.',
    projectId: 'lbo-industrial',
  },
  {
    id: 't-cpg-strategy',
    dealNumber: '#006',
    year: 2024,
    target: 'Fortune 500 CPG',
    subtitle: 'Enterprise strategy diagnostic · portfolio review',
    type: 'Corporate Strategy',
    size: '11 BUs · 9 countries',
    sector: 'Consumer Packaged Goods',
    role: 'Growth × ROIC portfolio grid · Divestiture case · Adjacencies',
    tools: ['Excel', 'PowerPoint', 'Tableau'],
    outcome: 'Recommended divestiture of two non-core BUs; $180M redeployment into two adjacent spaces.',
    projectId: 'strategy-fortune500',
  },
  {
    id: 't-vertical-ai',
    dealNumber: '#007',
    year: 2025,
    target: 'Vertical AI Analytics Co.',
    subtitle: 'Series C valuation advisory',
    type: 'Valuation · Growth Equity',
    size: '$340M–$410M range',
    sector: 'Enterprise Software · AI',
    role: 'Cohort-based revenue build · Rule-of-40 benchmarking · DCF',
    tools: ['Excel', 'Python', 'PitchBook'],
    outcome: 'Board-approved valuation band 9.5x forward ARR; triangulated 18 peers + 12 precedents.',
    projectId: 'valuation-vertical-ai',
  },
  {
    id: 't-apac-buyvsbuild',
    dealNumber: '#008',
    year: 2025,
    target: 'US SaaS Scaleup — APAC Entry',
    subtitle: 'Build-vs-buy strategy · target screening',
    type: 'Corporate Development',
    size: '$60M budget · 54 targets',
    sector: 'Enterprise SaaS',
    role: 'Organic build model · Target screen · Integration risk',
    tools: ['Excel', 'PitchBook', 'PowerPoint'],
    outcome: '54 → 6 shortlist; buy recommendation approved; LOI signed within 90 days.',
    projectId: 'corp-dev-apac',
  },
  {
    id: 't-fintech-india',
    dealNumber: '#009',
    year: 2025,
    target: 'India Fintech Landscape',
    subtitle: 'Market intelligence · six-segment sizing',
    type: 'Market Research',
    size: '184 companies mapped',
    sector: 'Financial Services · Fintech',
    role: 'TAM/SAM/SOM build · Competitive mapping · Regulatory heatmap',
    tools: ['Python', 'Excel', 'PowerPoint'],
    outcome: 'Anchored an inbound-strategy pivot worth an est. $12M ARR; 22 primary operator interviews.',
    projectId: 'market-fintech',
  },
  {
    id: 't-ai-deal-sourcing',
    dealNumber: '#010',
    year: 2025,
    target: 'PE Fund · AI Deal Sourcing',
    subtitle: 'Agentic screening pipeline · 1,200 co./week',
    type: 'AI Workflow',
    size: '4x analyst throughput',
    sector: 'Financial Sponsors',
    role: 'LangGraph orchestration · Playbook-driven memos',
    tools: ['Python', 'LangGraph', 'OpenAI', 'Postgres'],
    outcome: '71% precision vs. analyst baseline; 18 hours/week saved on repetitive screening.',
    projectId: 'ai-deal-sourcing',
  },
];

/* ---------------- Aspirational firms (pitchbook credentials wall) ---------------- */

export const ASPIRATIONAL_FIRMS = [
  {
    group: 'Bulge Bracket',
    firms: ['Goldman Sachs', 'Morgan Stanley', 'J.P. Morgan', 'Bank of America', 'Citi', 'UBS', 'Barclays', 'Deutsche Bank'],
  },
  {
    group: 'Elite Boutique',
    firms: ['Evercore', 'Lazard', 'Moelis & Company', 'Rothschild & Co', 'Centerview Partners', 'PJT Partners', 'Guggenheim', 'Perella Weinberg'],
  },
  {
    group: 'Strategy Consulting',
    firms: ['McKinsey & Company', 'Boston Consulting Group', 'Bain & Company', 'Strategy&', 'EY-Parthenon', 'Deloitte S&O', 'Kearney', 'Oliver Wyman'],
  },
  {
    group: 'Financial Sponsors',
    firms: ['Blackstone', 'KKR', 'Apollo', 'The Carlyle Group', 'TPG', 'Bain Capital', 'Warburg Pincus', 'Advent International'],
  },
];

/* ---------------- Projects (case studies) ---------------- */

export const PROJECTS = [
  {
    id: 'ma-tmt-2b',
    title: 'Cross-Border TMT Acquisition — Sell-Side Advisory',
    category: 'M&A',
    industry: 'Technology, Media & Telecom',
    year: 2024,
    accent: 'from-amber-500/30 to-rose-500/20',
    coverEmoji: '⌘',
    tags: ['M&A', 'DCF', 'Trading Comparables', 'Buyer Landscape', 'Synergy Bridge'],
    tools: ['Excel', 'PowerPoint', 'Capital IQ', 'Python'],
    impact: '$2.4B EV; 3 confirmatory bids at 14.6x forward EBITDA',
    metrics: [ { k: 'EV', v: '$2.4B' }, { k: 'Bidders 210→', v: '3' }, { k: 'Timeline', v: '11 wks' } ],
    featured: true,
    executiveSummary: 'Led modelling and buyer-landscape workstream on a sell-side mandate for a mid-market SaaS + connectivity platform. Built the operating model, DCF, LBO stress-case, and synergy scenarios that anchored the CIM. Prioritised 210 strategic and financial buyers into three confirmatory bids at a blended 14.6x forward EBITDA.',
    problem: 'Founders needed to test whether a strategic exit could out-price a continuation LBO within a 12-week window, while preserving competitive tension with 3+ credible bidders.',
    approach: [
      'Rebuilt the three-statement operating model bottoms-up from cohort ARR data.',
      'Framed three scenarios: base, downside recession, and synergy-adjusted strategic case.',
      'Ran a systematic buyer screen: 210 → 36 → 14 shortlisted with rationale memos.',
      'Owned the management-presentation storyline and Q&A rehearsal for the founders.',
    ],
    deliverables: ['Operating model (Excel)', 'CIM (46 pages)', 'Buyer landscape memo', 'Management-meeting deck'],
    learnings: 'The negotiation actually turns on synergy math, not standalone DCF. Building a defensible synergy bridge changed the anchor by ~1.8x EBITDA.',
    readingMinutes: 6,
  },
  {
    id: 'valuation-vertical-ai',
    title: 'Valuation — Vertical AI Analytics Company',
    category: 'Valuation',
    industry: 'Enterprise Software / AI',
    year: 2025,
    accent: 'from-violet-500/30 to-indigo-500/20',
    coverEmoji: '∫',
    tags: ['DCF', 'Trading Comparables', 'Rule of 40', 'Cohort Analysis'],
    tools: ['Excel', 'Python', 'PitchBook'],
    impact: 'Board-approved valuation range: $340M – $410M',
    metrics: [ { k: 'ARR', v: '$38M' }, { k: 'Rule of 40', v: '52' }, { k: 'Multiple', v: '9.5x' } ],
    featured: true,
    executiveSummary: 'Two-week valuation advisory for a vertical AI analytics company preparing a Series C. Delivered a triangulated range using DCF, trading comparables, and precedent transactions, anchored on a cohort-based bottom-up revenue build.',
    problem: 'Existing internal model used top-down TAM assumptions that could not withstand institutional diligence. Board needed a defensible range in under 10 business days.',
    approach: [
      'Rebuilt revenue from cohort-level net dollar retention on 4 years of billing data.',
      'Built a public-comps set of 18 vertical SaaS + AI-native peers with adjusted Rule-of-40 multiples.',
      'Triangulated with 12 precedent transactions since 2022.',
      'Sensitised WACC (10.5%–13.5%) and terminal growth (2.5%–4%).',
    ],
    deliverables: ['Valuation model (Excel)', 'Board memo (8 pages)', 'Multiples benchmarking pack'],
    learnings: 'The narrative around retention curves moved the multiple more than any WACC change. Cohorts are the story.',
    readingMinutes: 5,
  },
  {
    id: 'ai-deal-sourcing',
    title: 'AI Deal-Sourcing Workflow — Autonomous Screener',
    category: 'AI Automation',
    industry: 'Private Equity',
    year: 2025,
    accent: 'from-emerald-500/30 to-cyan-500/20',
    coverEmoji: '◐',
    tags: ['LangGraph', 'RAG', 'Screening', 'Playbook Automation'],
    tools: ['Python', 'LangGraph', 'OpenAI', 'PostgreSQL', 'Streamlit'],
    impact: '4x faster screening; 71% precision vs. analyst baseline',
    metrics: [ { k: 'Companies / week', v: '1,200' }, { k: 'Hours saved', v: '18/wk' }, { k: 'Precision', v: '71%' } ],
    featured: true,
    executiveSummary: 'Built an agentic pipeline that reads a fund thesis, screens 1,200+ private companies weekly across filings, product signals and hiring data, and produces one-pagers on the top 25 with citations.',
    problem: 'Fund partners were spending 40% of associate time on repetitive screening that only produced 3–4 meetings per week.',
    approach: [
      'Codified the fund thesis as a structured JSON playbook (must-have, nice-to-have, disqualifier).',
      'Multi-source ingestion: SEC/MCA filings, LinkedIn hiring, product changelogs, funding rounds.',
      'LangGraph agents for extract → score → memo, with citation-grounded generation.',
      'Human-in-the-loop review UI in Streamlit for partner sign-off.',
    ],
    deliverables: ['Python codebase', 'Fund-thesis playbook JSON', 'Weekly memo template', 'Handoff doc'],
    learnings: 'The bottleneck was not model quality — it was the fund thesis being ambiguous. Formalising the playbook was the actual win.',
    readingMinutes: 7,
  },
  {
    id: 'fpna-retail',
    title: 'Global Retailer — FP&A P&L Dashboard',
    category: 'Dashboards',
    industry: 'Consumer / Retail',
    year: 2024,
    accent: 'from-sky-500/25 to-blue-500/15',
    coverEmoji: '▤',
    tags: ['Power BI', 'Variance Analysis', 'Rolling Forecast'],
    tools: ['Power BI', 'DAX', 'SQL', 'Excel'],
    impact: 'Cut monthly close review from 3 days → 4 hours',
    metrics: [ { k: 'Countries', v: '17' }, { k: 'SKUs modelled', v: '9,400' }, { k: 'Refresh', v: 'Daily' } ],
    featured: true,
    executiveSummary: 'Executive P&L dashboard for a global retailer with 17-country operations. Drill-down from group P&L to store-level contribution margin, with actual vs. plan vs. rolling forecast variance.',
    problem: 'Finance business partners were spending three days per month reconciling regional P&Ls before commentary could begin.',
    approach: [
      'Star-schema data model in Power BI with fact-level partitioning.',
      'Waterfall variance visuals: price, volume, mix, FX.',
      'Auto-generated commentary drafts using a Python pre-processor.',
    ],
    deliverables: ['Power BI file', 'DAX measure library', 'FP&A commentary template'],
    learnings: 'Ninety percent of dashboard adoption comes from the first-load experience. Ruthless defaults matter.',
    readingMinutes: 4,
  },
  {
    id: 'market-fintech',
    title: 'Market Intelligence — Indian Fintech Landscape 2025',
    category: 'Market Research',
    industry: 'Financial Services',
    year: 2025,
    accent: 'from-fuchsia-500/25 to-pink-500/15',
    coverEmoji: '◈',
    tags: ['Market Sizing', 'Competitive Mapping', 'Regulatory'],
    tools: ['Python (scraping)', 'Excel', 'PowerPoint'],
    impact: 'Anchored an inbound-strategy pivot worth an est. $12M ARR',
    metrics: [ { k: 'Companies', v: '184' }, { k: 'Interviews', v: '22' }, { k: 'Segments', v: '6' } ],
    executiveSummary: 'A six-segment landscape of Indian fintech (UPI infra, lending, wealth, insurance, cross-border, embedded), with TAM/SAM/SOM builds, competitor deep-dives, and regulatory risk scoring.',
    problem: 'A cross-border wallet client had to decide which two of six segments to bet the next 18 months on.',
    approach: [
      'Bottom-up market sizing from RBI/NPCI + primary interviews.',
      'Competitor mapping on a 2x2 (product depth × distribution).',
      'Regulatory risk heatmap over the 2024–2026 policy window.',
    ],
    deliverables: ['85-page deck', 'Sizing model', 'Interview note bank'],
    learnings: 'Primary interviews with 22 operators corrected two of my early hypotheses. Never publish a landscape without them.',
    readingMinutes: 6,
  },
  {
    id: 'lbo-industrial',
    title: 'LBO Model — PE Take-Private of Industrial Coatings Co.',
    category: 'Valuation',
    industry: 'Industrials',
    year: 2024,
    accent: 'from-orange-500/25 to-red-500/15',
    coverEmoji: '⌥',
    tags: ['LBO', 'Debt Sizing', 'Returns Attribution'],
    tools: ['Excel', 'Python'],
    impact: 'Return bridge: 3.1x MOIC / 24% IRR (base case)',
    metrics: [ { k: 'EV', v: '$780M' }, { k: 'Leverage', v: '5.2x' }, { k: 'Hold', v: '5 yrs' } ],
    executiveSummary: 'A full LBO model for a take-private of a mid-cap industrial coatings company. Sources & uses, debt schedule with 3 tranches, operating cases (base, downside, ops-improvement), and returns bridge decomposition.',
    problem: 'Deal team needed a defensible returns bridge that explained how much of MOIC came from multiple, EBITDA growth, and deleveraging — before IC on Monday.',
    approach: [
      'Modelled 3 tranches: TLB, revolver, subordinated notes; covenant checks quarterly.',
      'Operating improvement case: 220 bps EBITDA margin uplift from procurement + pricing.',
      'Attribution: 44% EBITDA growth, 31% deleveraging, 25% multiple expansion.',
    ],
    deliverables: ['LBO model', 'IC memo (12 pages)', 'Sensitivity pack'],
    learnings: 'Attribution is what an IC actually debates. The bridge, not the IRR, is the artefact.',
    readingMinutes: 5,
  },
  {
    id: 'strategy-fortune500',
    title: 'Enterprise Strategy Diagnostic — Fortune 500 CPG',
    category: 'Corporate Strategy',
    industry: 'Consumer Packaged Goods',
    year: 2024,
    accent: 'from-teal-500/25 to-emerald-500/15',
    coverEmoji: '◇',
    tags: ['Portfolio Review', 'Where-to-play', 'Adjacencies'],
    tools: ['Excel', 'PowerPoint', 'Tableau'],
    impact: 'Divestiture recommendation on 2 non-core BUs; $180M redeployment',
    metrics: [ { k: 'BUs reviewed', v: '11' }, { k: 'Countries', v: '9' }, { k: 'Weeks', v: '8' } ],
    executiveSummary: 'Eight-week enterprise strategy diagnostic for a Fortune 500 CPG. Portfolio review across 11 business units on growth attractiveness × right-to-win. Recommended divestiture of two BUs and redeployment into two adjacencies.',
    problem: 'CEO had inherited a sprawling portfolio and needed a defensible where-to-play view for the board within Q2.',
    approach: [
      '2x2 portfolio grid; BU-level growth × ROIC; primary interviews with 18 BU heads.',
      'Adjacency map with 24 candidate spaces scored on 5 criteria.',
      'Financial redeployment simulation over a 5-year window.',
    ],
    deliverables: ['Board deck (52 pages)', 'Portfolio model', 'Interview synthesis'],
    learnings: 'Divestiture recommendations survive only if the redeployment story is equally sharp. Never present a where-not-to-play without a where-to-play.',
    readingMinutes: 6,
  },
  {
    id: 'ai-10k-extractor',
    title: 'Python Pipeline — SEC 10-K Financial Extraction',
    category: 'AI Automation',
    industry: 'Investment Research',
    year: 2024,
    accent: 'from-lime-500/25 to-green-500/15',
    coverEmoji: '⚑',
    tags: ['NLP', 'Structured Extraction', 'Data Pipeline'],
    tools: ['Python', 'OpenAI', 'PostgreSQL', 'Airflow'],
    impact: 'Automated 92% of a manual model-population workflow',
    metrics: [ { k: 'Filings / night', v: '450' }, { k: 'Accuracy', v: '97%' }, { k: 'Hours saved', v: '30/wk' } ],
    executiveSummary: 'Nightly pipeline that ingests fresh SEC 10-K filings, extracts a standardised 42-field financial schema with citations, and pushes into an internal database that feeds analyst models.',
    problem: 'Research team was manually populating comparable-company templates from filings, at ~4 hours per company.',
    approach: [
      'Section-aware chunking + LLM extraction with schema-forced JSON.',
      'Two-pass validation: numeric consistency + cross-year continuity.',
      'Airflow orchestration; failure alerts to Slack.',
    ],
    deliverables: ['Python codebase', 'Postgres schema', 'Runbook'],
    learnings: 'Numeric consistency checks caught more errors than any LLM prompt tuning. Validators are the moat.',
    readingMinutes: 5,
  },
  {
    id: 'dash-board-kpi',
    title: 'Board KPI Suite — SaaS Metrics Dashboard',
    category: 'Dashboards',
    industry: 'B2B SaaS',
    year: 2025,
    accent: 'from-indigo-500/25 to-violet-500/15',
    coverEmoji: '▣',
    tags: ['SaaS Metrics', 'Cohorts', 'Efficiency'],
    tools: ['Power BI', 'SQL', 'dbt'],
    impact: 'Adopted as the board pack primary artefact within 2 quarters',
    metrics: [ { k: 'Metrics', v: '38' }, { k: 'Cohorts', v: '48 mo' }, { k: 'Pages', v: '9' } ],
    executiveSummary: 'A board-grade SaaS metrics suite: ARR waterfall, NDR by cohort, magic number, burn multiple, sales efficiency, and rule-of-40 trajectory — all traceable to source rows.',
    problem: 'Board asks were fragmenting the finance team\'s time; every meeting produced a new custom pull.',
    approach: [
      'Canonical metric definitions signed off by CEO+CFO+VP Sales.',
      'dbt models for cohort tables; PBI for visual layer.',
      'Row-level drilldown from every headline number.',
    ],
    deliverables: ['PBIX file', 'dbt project', 'Metric glossary'],
    learnings: 'The metric definitions doc is a bigger deliverable than the dashboard. Ambiguity is expensive.',
    readingMinutes: 4,
  },
  {
    id: 'market-ev-europe',
    title: 'Competitive Intel — European EV Charging Networks',
    category: 'Market Research',
    industry: 'Energy / Mobility',
    year: 2024,
    accent: 'from-cyan-500/25 to-sky-500/15',
    coverEmoji: '◉',
    tags: ['Competitive Landscape', 'Site Economics', 'Regulation'],
    tools: ['Python', 'Excel', 'PowerPoint'],
    impact: 'Informed a €90M capex reallocation to Iberia + Nordics',
    metrics: [ { k: 'Networks', v: '46' }, { k: 'Sites analysed', v: '3,200' }, { k: 'Countries', v: '11' } ],
    executiveSummary: 'A competitive map of European EV charging networks across 11 countries, with unit economics per site archetype, and a regulatory calendar of subsidy sunset dates.',
    problem: 'An operator client had capex committed to five countries but needed to reallocate to the two with best unit economics under new subsidy rules.',
    approach: [
      'Web-scraped site inventories and charge-session pricing across 46 networks.',
      'Built a site-archetype unit model (utilisation × price × opex).',
      'Regulatory timeline over 2024–2027 by country.',
    ],
    deliverables: ['Competitive deck', 'Site-economics model', 'Regulatory calendar'],
    learnings: 'Unit economics dispersion inside a country was greater than between countries. Site archetype matters more than geography.',
    readingMinutes: 5,
  },
  {
    id: 'corp-dev-apac',
    title: 'Corporate Development — APAC Build vs. Buy',
    category: 'Corporate Strategy',
    industry: 'Enterprise SaaS',
    year: 2025,
    accent: 'from-rose-500/25 to-amber-500/15',
    coverEmoji: '⟁',
    tags: ['Build-vs-Buy', 'Target Screening', 'Integration'],
    tools: ['Excel', 'PitchBook', 'PowerPoint'],
    impact: 'Approved buy recommendation; LOI signed within 90 days',
    metrics: [ { k: 'Targets screened', v: '54' }, { k: 'Deep dives', v: '6' }, { k: 'LOI', v: 'Signed' } ],
    executiveSummary: 'A 10-week build-vs-buy analysis for entering APAC as a US SaaS scaleup. Compared organic build cost & timeline against acquisition of a local incumbent, screening 54 targets to a shortlist of 6.',
    problem: 'Leadership had to choose within a fiscal year — build a Singapore hub or acquire an incumbent — with a $60M budget.',
    approach: [
      'Organic build model: hiring plan, GTM ramp, unit economics dilution.',
      'Target screen: 54 → 6 with a scoring rubric across product fit, GTM, culture, price.',
      'Integration risk assessment for the top 2 candidates.',
    ],
    deliverables: ['Build-vs-buy model', 'Target longlist', 'Board memo', 'Integration risk matrix'],
    learnings: 'The build case looks cheapest on paper and slowest in reality. Explicitly modelling the time-to-first-dollar changed the decision.',
    readingMinutes: 6,
  },
];

export const CATEGORIES = ['All', 'M&A', 'Valuation', 'Corporate Strategy', 'AI Automation', 'Dashboards', 'Market Research'];

export const SKILLS = [
  { group: 'Finance & Valuation', items: ['Three-Statement Model', 'DCF', 'LBO', 'Trading Comparables', 'Precedent Transactions', 'Sensitivity & Scenario Analysis', 'Returns Bridge Attribution', 'Debt Sizing', 'Operating Model'] },
  { group: 'Strategy & Research', items: ['Corporate Strategy', 'Market Sizing (TAM/SAM/SOM)', 'Competitive Intelligence', 'Due Diligence', 'Portfolio Review', 'Build-vs-Buy', 'Board Communication', 'Investment Memo'] },
  { group: 'Data & Engineering', items: ['Python', 'SQL', 'Power BI', 'DAX', 'dbt', 'Tableau', 'Excel (advanced)', 'PowerPoint (executive)', 'Capital IQ', 'PitchBook', 'Bloomberg'] },
  { group: 'AI & Automation', items: ['LLM Workflows', 'LangGraph', 'RAG', 'Structured Extraction', 'Prompt Design', 'Human-in-the-loop', 'Agentic Screening'] },
];

export const EXPERIENCE = [
  {
    company: 'Meridian Corporate Advisory',
    role: 'Associate, M&A + Strategic Finance',
    period: '2023 — Present',
    location: 'Mumbai / Singapore',
    bullets: [
      'Led modelling on 6 sell-side and buy-side mandates aggregating $3.1B EV.',
      'Built the firm\'s AI deal-sourcing pipeline; now used across 3 sector teams.',
      'Trained 4 analysts on valuation methods and Power BI dashboarding.',
    ],
  },
  {
    company: 'Northgate Consulting',
    role: 'Senior Business Analyst, Strategy',
    period: '2021 — 2023',
    location: 'Bangalore',
    bullets: [
      'Delivered enterprise strategy diagnostics for CPG and industrials clients.',
      'Rebuilt the firm\'s market-sizing template; adopted across the practice.',
    ],
  },
  {
    company: 'Fortis Capital (FP&A)',
    role: 'Analyst, Financial Planning & Analysis',
    period: '2019 — 2021',
    location: 'Pune',
    bullets: [
      'Owned the quarterly rolling forecast for a $220M revenue division.',
      'Automated month-end variance reporting using SQL + Power BI.',
    ],
  },
];

export const EDUCATION = [
  {
    id: 'edu-1',
    degree: 'MBA · Finance & Strategy',
    institution: 'Indian School of Business (ISB)',
    period: '2017 — 2019',
    location: 'Hyderabad',
    details: 'Dean\'s List. Concentrations in Corporate Finance, Investment Banking, and Strategy. Investment Club — Head of Equity Research.',
  },
  {
    id: 'edu-2',
    degree: 'B.Com (Hons.) · Accounting & Finance',
    institution: 'Shri Ram College of Commerce, University of Delhi',
    period: '2014 — 2017',
    location: 'New Delhi',
    details: 'First class with distinction. Finance Society core team. Regional finalist, ITC Interrobang case competition.',
  },
];

export const CERTIFICATIONS = [
  { id: 'cert-1', name: 'CFA Level II Candidate', issuer: 'CFA Institute', year: 2025, credentialUrl: '' },
  { id: 'cert-2', name: 'Financial Modeling & Valuation Analyst (FMVA)', issuer: 'Corporate Finance Institute', year: 2023, credentialUrl: '' },
  { id: 'cert-3', name: 'Advanced Financial Modeling (M&A + LBO)', issuer: 'Wall Street Prep', year: 2023, credentialUrl: '' },
  { id: 'cert-4', name: 'Microsoft Power BI Data Analyst (PL-300)', issuer: 'Microsoft', year: 2022, credentialUrl: '' },
  { id: 'cert-5', name: 'Python for Finance — Applied', issuer: 'DataCamp', year: 2022, credentialUrl: '' },
];

export const TESTIMONIALS = [
  {
    id: 'test-1',
    quote: 'Deepak\'s LBO model was the first one I did not have to rebuild from scratch. He owned the returns bridge and walked the IC through it like a senior associate.',
    name: 'Priya Ramanathan',
    title: 'Managing Director, M&A',
    company: 'Meridian Corporate Advisory',
    avatarUrl: '',
  },
  {
    id: 'test-2',
    quote: 'The buyer landscape and synergy bridge Deepak built anchored a $2.4B mandate. Sharp modelling, sharper communication.',
    name: 'Arjun Malhotra',
    title: 'Partner, TMT Coverage',
    company: 'Elite Boutique Advisory',
    avatarUrl: '',
  },
  {
    id: 'test-3',
    quote: 'He rewrote our market-sizing template. Two years later it is still the firm standard.',
    name: 'Sneha Iyer',
    title: 'Principal',
    company: 'Northgate Consulting',
    avatarUrl: '',
  },
  {
    id: 'test-4',
    quote: 'The AI deal-sourcing pipeline changed how our associates start every Monday. Precision on the memos was materially better than our baseline.',
    name: 'Rahul Bhatia',
    title: 'Partner, Growth Equity',
    company: 'Private Equity Fund (undisclosed)',
    avatarUrl: '',
  },
];

export const SEO_DEFAULTS = {
  title: 'Deepak — Investment Banking, Strategic Finance & M&A',
  description: 'Institutional-grade financial intelligence — DCF, LBO, M&A execution, corporate development, and AI-augmented deal workflows. Selected transactions, case studies, and downloadable analytics artefacts.',
  keywords: 'Investment Banking, Strategic Finance, M&A, Valuation, DCF, LBO, Corporate Development, FP&A, AI for Finance, Portfolio, Deepak',
  ogImageUrl: '',
};

// Composed seed used by the API to initialise the mutable site_content document.
export const SEED_CONTENT = {
  owner: OWNER,
  chapters: CHAPTERS,
  categories: CATEGORIES,
  projects: PROJECTS,
  skills: SKILLS,
  experience: EXPERIENCE,
  transactions: TRANSACTIONS,
  aspirations: ASPIRATIONAL_FIRMS,
  expertise: EXPERTISE_CHIPS,
  education: EDUCATION,
  certifications: CERTIFICATIONS,
  testimonials: TESTIMONIALS,
  seo: SEO_DEFAULTS,
};

// Accent gradient options exposed in the admin (kept in sync with card renderer).
export const ACCENT_OPTIONS = [
  'from-amber-500/30 to-rose-500/20',
  'from-violet-500/30 to-indigo-500/20',
  'from-emerald-500/30 to-cyan-500/20',
  'from-sky-500/25 to-blue-500/15',
  'from-fuchsia-500/25 to-pink-500/15',
  'from-orange-500/25 to-red-500/15',
  'from-teal-500/25 to-emerald-500/15',
  'from-lime-500/25 to-green-500/15',
  'from-indigo-500/25 to-violet-500/15',
  'from-cyan-500/25 to-sky-500/15',
  'from-rose-500/25 to-amber-500/15',
];

export const CATEGORY_OPTIONS = ['M&A', 'Valuation', 'Corporate Strategy', 'AI Automation', 'Dashboards', 'Market Research'];
